import org.eclipse.jdt.ui.text.java.IQuickFixProcessor;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args){
    		int a = getA();
    }
}
